version: '3.8'
services:
  postgres:
    image: postgres:9.6
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
      - webserver
    env_file:
      - .env
    ports:
      - '8793:8793'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: scheduler

  webserver:
    build: .
    restart: always
    entrypoint: ./scripts/entrypoint.sh
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
